spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall
    initialSize: 5
    minIdle: 5
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    maxEvictableIdleTimeMillis:  3000000 # 因为公司防火墙长连接保持最长时间为1小时；此参数一定要结合实际情况进行配置。
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000

lock:
  module1:
    lockKey: lock
    lockExpiryInMsec: 300
  redis:
    #cluster:
    #nodes:
    #- 127.0.0.1:6379
    #- 127.0.0.1:6378
    #- 127.0.0.1:6377
    # Redis数据库索引（默认为0）
#    database: 10
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 1800
    # 密码
    #password:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 1500
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: 2048
      # 连接池中的最小空闲连接
      min-idle: 20
      # 连接池中的最大空闲连接
      max-idle: 200
